apiVersion: v1
kind: Secret
metadata:
  name: jitsu-env
  labels:
{{ include "jitsu.labels" . | indent 4 }}
stringData:
  REDIS_URL: redis://:{{ .Values.secrets.redis_password }}@{{ .Values.secrets.redis_host }}:6379
  CLUSTER_ADMIN_TOKEN: {{ .Values.secrets.admin_token }}
  JITSU_CONFIGURATOR_URL: {{ .Values.secrets.configurator_url }}
  USER_RECOGNITION_ENABLED: 'true'
  USER_RECOGNITION_REDIS_URL: redis://:{{ .Values.secrets.redis_password }}@{{ .Values.secrets.redis_host }}:6379
  TLS_SKIP_VERIFY: 'true'
  TERM: xterm-256color
  {{ if .Values.secrets.sso }}
  JITSU_SSO_CONFIG: {{ toJson .Values.secrets.sso | quote }}
  {{ end }}
  {{ if .Values.secrets.smtp }}
  JITSU_SMTP_CONFIG: {{ toJson .Values.secrets.smtp | quote }}
  {{ end }}
  {{- if .Values.airbyte.enabled }}
  DOCKER_HOST: tcp://localhost:2375
  SERVER_VOLUMES_WORKSPACE: /tmp/airbyte/
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jitsu-config
  labels:
{{ include "jitsu.labels" . | indent 4 }}
stringData:
  eventnative.yaml: |
    {{ toYaml .Values.config | nindent 4 }}